pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Data-base') {
      agent {
        docker { image 'mysql:8.0' }
      }
      environment {
        MYSQL_ROOT_PASSWORD = 'rootpassword' // Set MySQL root password
      }
      steps {
        sh '''
          echo "CREATE DATABASE test_db;" | mysql -u root -p$MYSQL_ROOT_PASSWORD
          echo "USE test_db; CREATE TABLE XYZ (id INT);" | mysql -u root -p$MYSQL_ROOT_PASSWORD
          echo "USE test_db; INSERT INTO XYZ VALUES (1);" | mysql -u root -p$MYSQL_ROOT_PASSWORD
          echo "USE test_db; SELECT * FROM XYZ;" | mysql -u root -p$MYSQL_ROOT_PASSWORD
        '''
      }
    }
  }
}
